blogApp/urls.py
from django.urls import path
from .import views
# from  .views import PostListView

app_name = 'blogApp'

urlpatterns = [
    # path('Search/', views.Search_Item, name='Search_Page'),
    path('', views.PostListView, name='Home_Page'),
    path('bookmark/<int:id>/', views.bookmark, name='Bookmark_Page'),
    path('bookmarked/', views.bookmarked, name='Bookmarked_Page'),
    path('Settings/', views.Settings, name='Settings_Page'),
    path('Profile/', views.Profile, name='Profile_Page'),
    path('Update_Profile/', views.Update_Profile, name='UpdateProfile_Page'),
    path('likes/', views.likes, name='likes'),
    path('<slug:S_post>/', views.Single_Post, name='Single_Post'),
    path('Category/<Category>/', views.CategoryListView.as_view(), name='Category'),
] 

infoHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from Users import views as UserLoginView
from Users import views as User_Views
from blogApp import views as User_Views2
from django.contrib.auth import views as auth_views
from Users.forms import PwdResetConfirmForm, PwdChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Register/', User_Views.Register, name='Register_Page'),
    path('Login/', User_Views.Login, name='Login_Page'),
    path('Logout/', User_Views.Logout, name='Logout_Page'),
    path('Password_Reset/', User_Views.PasswordResetFormPage.as_view(), name='Password_Reset_Page'),
    path('Password_Reset_Done/', User_Views.PassowrdResetDonePage.as_view(), name='password_reset_done'),
    path('Password_Reset_Confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='Users/password_reset_confirm.html', form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('Password_Reset_Complete/', auth_views.PasswordResetCompleteView.as_view(template_name='Users/password_reset_complete.html'), name='password_reset_complete'),
    path('Change_Password/', auth_views.PasswordChangeView.as_view(template_name='Users/password_change.html', form_class=PwdChangeForm), name='Password_Change_Page'),
    path('Password_Done', auth_views.PasswordChangeDoneView.as_view(template_name='Users/password_change_done.html'), name='password_change_done'),
    path('delete/', User_Views2.Delete, name='Delete_Page' ),
    path('', include('blogApp.urls', namespace='blogApp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image  
import os


def  User_Directory_Path(instance, filename):
    return 'Posts/{0}/{1}'.format(instance.id, filename)

class Category(models.Model):
    name = models.CharField(max_length=2000)

    def __str__(self):
        return self.name

# Making A form for post
class Post(models.Model):

    #for filtering out draft and published post that displays on the web
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(Status='published')
        
    #Status Option Data
    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    Title = models.CharField(max_length=250)
    First_Name = models.CharField(max_length=15)
    Last_Name = models.CharField(max_length=15)
    Email = models.EmailField(max_length=30)
    slug = models.SlugField(max_length=250, unique_for_date='Publish', default='default')
    Publish = models.DateTimeField(default=timezone.now )
    Author = models.ForeignKey (User, on_delete=models.CASCADE, related_name='blog_posts')
    Content = models.TextField()
    Category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    Category_Tag = models.CharField(max_length=20, default='Default')
    Image = models.ImageField(upload_to=User_Directory_Path)
    Status = models.CharField(max_length=10, choices=options, default='draft')
    Objects = models.Manager() #default Manager
    Newmanager = NewManager() #custom manager
    likes_count = models.IntegerField(default='0')
    likes = models.ManyToManyField(User, related_name='like', default=None, blank=True)
    liked = models.BooleanField(default=False)
    bookmark_count =  models.IntegerField(default=0)
    bookmark = models.ManyToManyField(User, related_name='bookmark',default=None, blank=True )


    #to get to each individual post from a link
    def get_absolute_url(self):
        return reverse('blogApp:Single_Post', args=[self.slug])
    
  
    #ordering the list of post from latest to least latest
    class Meta:
        ordering = ('-Publish',)[:8]

    #making Human Readable text on post title in the database
    def __str__(self):
        return self.Title
    
class Comment(models.Model):
    Post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='Comment' )
    Name = models.CharField(max_length=20)
    Email = models.EmailField(max_length=25)
    Comment = models.TextField(max_length=270)
    Publish = models.DateTimeField(default=timezone.now)
    Status = models.BooleanField(default=True)

    class Meta:
        ordering = ('-Publish',)

    def __str__(self):
        return f"Comment by {self.Name}"
    

blogApp/forms.py
from django import forms
from .models import Comment

class NewCommentForm(forms.ModelForm):
    Comment = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':200 , 'class':'textarea','placeholder':'Comment'}))

    class Meta:
        model = Comment
        fields = ['Comment']




# class SearchForm(forms.Form):
#     Search_Input = forms.CharField()

blogApp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
# from Users.models import Profile
from .models import Post #Comment
from .forms import NewCommentForm  # SearchForm#
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from Users.forms import UserProfileUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.http import  JsonResponse
from django.db.models import Count
from django.core.paginator import Paginator
import json

@login_required
def bookmarked(request):
    bookmarked_post = Post.Newmanager.annotate(num_comments=Count('Comment')).filter(bookmark = request.user)
    return render(request, 'blogApp/bookmark.html', {'bookmarked_post': bookmarked_post})

@login_required
def bookmark(request, id):
   post = get_object_or_404(Post, id=id)
   if post.bookmark.filter(id=request.user.id).exists():
       post.bookmark.remove(request.user)
       post.bookmark_count -= 1
       post.save()
       messages.success(request, 'Bookmark Removed Successfully')

   else:
       post.bookmark.add(request.user)
       post.bookmark_count += 1
       post.save()
       messages.success(request, 'Bookmark Added Successfully')

   return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def likes(request):
   if request.POST.get('action') == 'post':
       result = ''
       post_id = int(request.POST.get('postid'))
       post = get_object_or_404(Post, id=post_id)
       
       if post.likes.filter(id=request.user.id).exists():
           post.likes.remove(request.user)
           post.likes_count -= 1
           result = post.likes_count
           post.liked = False
           post.save()
       else:
           post.likes.add(request.user)
           post.likes_count  += 1
           result = post.likes_count
           post.liked = True
           post.save()


       return JsonResponse({'result':result, 'liked':post.liked,})
   
@login_required
def Delete(request):
    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        user.is_active = False
        user.save()
        messages.success(request,'Account Successfully Deleted!' )
        return redirect('Login_Page') 
    
    return render(request, 'Users/delete.html')

@login_required
def Settings(request):
    return render(request, 'blogApp/settings.html' )

@login_required
def Profile(request):
    return render(request, 'blogApp/Profile.html' )

@login_required
def Update_Profile(request):
    if request.method == 'POST':
        UserProfileUpdate = UserProfileUpdateForm(request.POST, instance=request.user, request = request)
        ProfileUpdate = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if UserProfileUpdate.is_valid() and ProfileUpdate.is_valid():
            UserProfileUpdate.save()
            ProfileUpdate.save()
            messages.success(request, f'Your Profile has been updated successfully!')
            return redirect('blogApp:UpdateProfile_Page')
    
    else:
        UserProfileUpdate = UserProfileUpdateForm(instance=request.user, request = request)
        ProfileUpdate = ProfileUpdateForm(instance=request.user.profile)
    
    FileName = request.user.profile.file_name
    context = {
        'UserProfileUpdate' : UserProfileUpdate,
        'ProfileUpdate' : ProfileUpdate,
        'FileName': FileName
    }

    return render(request, 'blogApp/Update_Profile.html', context)

@login_required
def PostListView(request):
    updated_posts = Post.Newmanager.annotate(num_comments=Count('Comment')).order_by('-Publish')[:6]
    older_posts = None
   
    if len(updated_posts) > 6:
         older_posts = Post.Newmanager.annotate(num_comments=Count('Comment')).order_by('Publish')[:6]

    context = {'Updated_Post': updated_posts,
               'Older_Post': older_posts,
            }
    
    return render(request, 'blogApp/index.html', context)

@login_required
def Single_Post(request, S_post):
    S_post =  get_object_or_404(Post, slug=S_post, Status='published')
    Comment = S_post.Comment.filter(Status=True)

    comments_per_page = 2
    paginator = Paginator(Comment, comments_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    user_comment = None
    O_post = Post.Newmanager.annotate(num_comments=Count('Comment')).filter(Status='published').exclude(id=S_post.id)[:5]
    
    if request.user.is_authenticated:
        username = request.user.username
        email = request.user.email

        if request.method == 'POST':
            comment_form = NewCommentForm(request.POST)

            if comment_form.is_valid(): 
                user_comment = comment_form.save(commit=False)
                user_comment.Name = username  
                user_comment.Email = email  
                user_comment.Post = S_post
                user_comment.save()
                return HttpResponseRedirect('/' + S_post.slug)
        else:
            comment_form = NewCommentForm()

        return render(request, 'blogApp/Single_Post.html', 
                    {'S_post': S_post,
                    'user_comment' : user_comment, 
                    'Comment' : Comment,
                    'comment_form': comment_form,
                    'O_post' : O_post,
                    'page':page })
    else:
        pass


class CategoryListView(LoginRequiredMixin,  ListView):
    template_name = 'blogApp/Category_Pages.html'
    context_object_name = 'Category_List'

    def get_queryset(self):
       Category_Content = {
            #Captures a specific category Name  to the template
            'Category' : self.kwargs['Category'],
            #Collects all data from the post ||filters post from the specific category name  to specific category pages|| filters again to only published posts
            'Category_Post' : Post.Objects.annotate(num_comments=Count('Comment')).filter(Category__name=self.kwargs['Category']).filter(Status='published')
        } 
       return Category_Content
    

# def Search_Item(request):
#     Form = SearchForm()
#     Query = ''
#     Search_Result = []

#     #checking to see if data exist in the Get request
#     if 'Query' in request.GET:
#         #Processing the information in request
#         Form = SearchForm(request.GET)
#         #checking to see if form is valid
#         if Form.is_valid():
#             #if form is valid, the data should be returned
#             Query = Form.cleaned_data['Query']
#             #Looking for the posts in the database that contains the query
#             Search_Result = Post.Objects.filter(Title__contains=Query)
  

#     return render(request, 'blogApp/Search.html', 
#                   {'Form':Form,
#                    'Query': Query,
#                    'Search_Result':Search_Result})


blogApp/templates/blogApp/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} Info Hub {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/Main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script> -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="RemoveNav">
        <div class="Wrapper">
            <nav>
               <img class="Logo" src="{% static 'media\Logo.png' %}" alt="Logo">
 
                    <ul>
                        <li><a href="{% url 'blogApp:Home_Page' %}">Home</a></li>
                        <li><a href="#" class="OpenCategoryList">Category</a></li>
                        <li><a href="#">Search</a></li>
                    </ul>

                    <img src="{{user.profile.image.url}}" alt="Default-Image"  class="MoreLink" >

                    <div class="Category-option CategoryList">
                        <div class="Category-Option-List">

                            {% for Category_List_Item in Category_List_Options %}
                                <li>
                                    <a href="/Category/{{Category_List_Item.name}}">{{Category_List_Item.name}}</a>
                                    <i class="fa fa-angle-right"></i>
                                </li>
                            {% endfor %}

                            
                        </div>
                     </div>


                    <div class="Sub-Profile-Wrap SideProfile">
                            <div class="Sub-Profile">
                               <div class="User-Info">
                                <!-- Image size 256 × 256 px -->
                                <img src="{{user.profile.image.url}}" alt="Default-Image">
                                    <div class="Users">
                                        <h3>{{user.first_name}} &nbsp;{{user.last_name}}</h3>
                                        <h5>{{user.username}}</h5>
                                        <p>{{user.email}}</p>
                                    </div>
                               </div>
                               <hr>
 
                               <div id="ResNav" class="User-Info-Options">

                                <a href="{% url 'blogApp:Home_Page' %}" class="Sub-Menu-Links">
                                    <i class="fa fa-home"></i>
                                    <p>Home</p>
                                    <span><i class="fa fa-angle-right"></i></span>
                                </a>

                                <a href="#" class="Sub-Menu-Links">
                                    <i class="fa fa-database"></i>
                                    <p class="OpenCategoryList2">category</p>
                                    <span><i class="fa fa-angle-down"></i></span>
                                </a>

                                  <div class="RevOpts CategoryList2">
                                    <div class="Category-Option-List">
                 
                                     {% for Category_List_Item in Category_List_Options %}
                                        <li>
                                            <a href="/Category/{{Category_List_Item.name}}">{{Category_List_Item.name}}</a>
                                            <i class="fa fa-angle-right"></i>
                                        </li>
                                    {% endfor %}

                                   </div>
           
                                  </div>
                                 
                                
                                <hr>

                            </div>
                              

                                <div class="User-Info-Options">

                                    <a href="{% url 'blogApp:Bookmarked_Page' %}" class="Sub-Menu-Links">
                                        <i class="fa fa-heart"></i>
                                        <p>Bookmark</p> 
                                        <span><i class="fa fa-angle-right"></i></span>
                                    </a>

                                    <a href="{% url 'blogApp:Settings_Page' %}" class="Sub-Menu-Links">
                                        <i class="fa fa-cogs"></i>
                                        <p>Settings</p>
                                        <span><i class="fa fa-angle-right"></i></span>
                                    </a>

                                           
                                     {% if user.is_authenticated %} 
                                    <a href="{% url 'Logout_Page' %}" class="Sub-Menu-Links">
                                        <i class="fa fa-mail-reply-all"></i>
                                        <p>Logout</p>
                                        <span><i class="fa fa-angle-right"></i></span>
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                    </div>

            </nav>


            
            {% block templates %}
            {% endblock %}

            <!-- <div class="Footer">

                <div class="Footer-Wrapper">
            
                    <div class="Footer-Top-Content">
                        <a href="#">About Us</a>
                        <a href="#">Contact Us</a>
                        <a href="#">Terms</a>
                        <a href="#">Privacy Policy</a>
                        <a href="#">Disclaimer</a>
                    </div>
            
                    <div class="Footer-Bottom-Content">
                        <p>...Blog designed and developed by <span>Xhicko</span></p>
                    </div>
                </div>
            
            </div>  -->

        </div>

    <script src="{% static 'js/Index.js' %}"></script>

</body>
</html>




blogApp/templates/blogApp/Single_Post.html
    {% extends "blogApp/Base.html" %}
    {% block title %}Post Content{% endblock %}
        {% load static %}
        {% block templates %} 

    <div class="Post_View">

        <div class="Full_Post_Wrapper">

            <div id="popup-message">
               Link Copied Successfully 
            </div>

             {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div class="SuccessMessages Msg Msg2">
                        <p>{{ message }}</p>
                    </div> 
                {% endif %}
             {% endfor %}
           {% endif %}
           
            <div class="Main_Post_Wrapper">
                <div class="Main_Post_Details">
                    <div class="Main_Post_Details_Header">
                        <h1>{{S_post.First_Name}} {{S_post.Last_Name}}</h1>
                        <h1>{{S_post.Publish}}</h1>
                    </div>
            
                    <img  class="Main_Post_Details_Image" src="{{S_post.Image.url}}" alt="{{S_post.Category_Tag}}">
            
                    <div class="Main_Post_Details_Content">
                        <h1>{{S_post.Title}}</h1>
                        <p>{{S_post.Content}}</p>
                    </div>
            
                    <div class="Main_Post_Details_Meta_Info">
                        <div class="Reaction_Info">
                            <div class="Item_Info">
                                <span id="likes_check">{{S_post.likes_count}}</span>
                                &nbsp;<p>likes</p>
                            </div>
                            <div class="Item_Info">
                                <span>{{S_post.bookmark_count}}</span>
                                &nbsp;<p>Bookmarks</p>
                            </div>
                    
                           
                            <div class="Item_Info">
                                {% with Comment.count as total_comments %}
                                <span>{{total_comments}}</span>
                                {% endwith %}
                                &nbsp;<p>Comment</p>
                            </div>
                        </div>
                        <hr>
                        <div class="Reactions">
                            <div class="item Favourites">
                                <a href="{% url 'blogApp:Bookmark_Page' S_post.id %}"><i  class="fa fa-bookmark"></i></a>
                                <p>{{S_post.bookmark_count}}</p>
                            </div>
                    
                            <div class="item Likes">
                    
                                {% if post.liked %}
                                <i id="likes_button" data-postid="{{S_post.id}}" class="fa fa-heart liked "></i>
                                {% else %}
                                <i id="likes_button" data-postid="{{S_post.id}}" class="fa fa-heart "></i>
                                {% endif %}
                    
                                <p id="likes_count">{{S_post.likes_count}}</p>
                            </div>
                    
                            
                            <div class="item Comment">
                                <i  class="fa fa-comment"></i>
                                {% with Comment.count as total_comments %}
                                    <p>{{total_comments}}</p>
                                {% endwith %}
                            </div>
                    
                            <div class="item Share">
                                <i  class="fa fa-share-alt" onclick="copyToClipboard()"></i>
                            </div>
                    
                        </div>
                    </div>
    
                    <div class="Main_Post_Details_Footer">
                        <p>{{S_post.Email}}</p>
                        <a href="{% url 'blogApp:Home_Page' %}">Back</a>
                    </div>
                </div>
    
            </div>
    
            <div class="Make_Comment">      
                <h1>Make a new comment</h1>
                <form  id="Comment_Form" method="post">
                    {{comment_form.Comment}}
                    {% csrf_token %}
                    <button class="btn" type="submit">submit</button>
                </form>
            </div>
    
         
            {% if Comment %}
            <div class="Comment_Posted">
                <h1>Latest Comments</h1>
                {% for UserComment in page %}
                        <div class="Comment_Wrapper">     
                            <div class="Comment_Posted_Info">
                                <h3> comment by {{UserComment.Name}}</h3>
                                <h3>{{UserComment.Publish}}</h3>
                        </div>
                        <p>{{UserComment.Comment|truncatechars:270}}</p>
                        </div>
                   
                {% endfor %}
            </div>
            {% else %}
                <div class="No_Comment_Available">
                    <p>No comments available</p>
                </div>
            {% endif %}

            
             {% if page %}
            <div class="pagination">
    
        
                <div class="Page_Left Ltn">
            
                    {% if page.has_previous %}
            
                        <div  class="Page_Btn">
                        <a href="?page={{ page.previous_page_number }}">Previous</a>
            
                        </div>
            
                    {% else %}
            
                        <div class="Page_Btn Disabled">
                            Previous
                        </div>
            
                    {% endif %}
            
                </div>
            
            
                <div class="Page_Center">
                    {% for num in page.paginator.page_range %}
                        {% if page.number == num %}
            
                            <div class="Current_Page">
                                {{ num }}
                            </div>
                            
                        {% else %}
            
                            <div class="Page_Num">
                            {{ num }}
                            </div>
            
                        {% endif %}
                    {% endfor %}
                </div>
            
            
                <div class="Page_Right Ltn">
            
                {% if page.has_next %}
                    <div class="Page_Btn">
                    <a href="?page={{ page.next_page_number }}">Next</a>
                    </div>
            
                {% else %}
            
                <div class="Page_Btn Disabled">
                    Next
                </div>
            
                {% endif %}
                </div>
            
            </div> 
            {% endif %}
    

       </div>
    
       <div class="Side_Post_Wrapper">
        {% if O_post %}
                <h1>Other Posts</h1>
                {% for Side_Post_Content in O_post %}
                    <div class="Side_Post_Content">

                        <div class="Side_Post_Content_Top">
                            <img src="{{Side_Post_Content.Image.url}}" alt="{{Side_Post_Content.Category_Tag}}">
                        </div>

                        <div class="Side_Post_Content_Middle">
                            <a href="{{Side_Post_Content.get_absolute_url}}">
                               <p> {{ Side_Post_Content.Title|truncatechars:35 }}</p>
                            </a>
                        </div>

                        <div class="Side_Post_Content_Footer">
                            <div class="SPC_Footer_Top">
                                <h3>{{Side_Post_Content.Category_Tag}}</h3>
                                <h3>By {{Side_Post_Content.Last_Name }}</h3>
                            </div>

                            <div class="SPC_Footer_Bottom">

                                <div class="Side_Post_Reaction_item SPRI_Likes">
                                    <i  class="fa fa-heart"></i>
                                    <p>{{Side_Post_Content.likes_count}}</p>
                                </div>

                                 <div class="Side_Post_Reaction_item  SPRI_Favourites">
                                    <i  class="fa fa-bookmark"></i>
                                    <p>{{Side_Post_Content.bookmark_count}}</p>
                                </div>

                           
                                <div class="Side_Post_Reaction_item  SPRI_Comments">
                                    <i  class="fa fa-comment"></i>
                                    
                                    <p>{{Side_Post_Content.num_comments}}</p>
                                </div>

                            </div>
                        </div>
            

                    </div>


                {% endfor %}

        {% endif %}
       </div>

    </div>


<script>

function hideFlashMessages() {
    const flashMessages = document.querySelectorAll('.SuccessMessages');
    flashMessages.forEach((message) => {
        setTimeout(() => {
            message.style.display = 'none';
        }, 3000); 
    });
}

document.addEventListener('DOMContentLoaded', function() {
    hideFlashMessages();
});

$(document).ready(function() {
    var postId = $('#likes_button').data('postid');
    var csrfToken = $('input[name=csrfmiddlewaretoken]').val();

    // Check if the liked status is stored in the session
    var liked = sessionStorage.getItem('liked_' + postId);
    if (liked === 'true') {
        $('#likes_button').addClass('liked');
    }

    // Bind click event to update like status
    $(document).on('click', '#likes_button', function(e) {
        e.preventDefault();
        var icon = $(this);

        // Send AJAX request to update the like status
        $.ajax({
            type: 'POST',
            url: '/likes/',
            data: {
                postid: postId,
                action: 'post',
                csrfmiddlewaretoken: csrfToken
            },
            success: function(json) {
                document.getElementById('likes_check').innerHTML = json['result']
                // document.getElementById('likes_count').innerHTML = json['result']
                var result = json['result'];
                var liked = json['liked'];

                // Update the likes count
                $('#likes_count').text(result);

                // Store the updated like status in the session 
                sessionStorage.setItem('liked_' + postId, liked);

                // Apply or remove the 'liked' class based on the updated like status
                if (liked) {
                    icon.addClass('liked');
                } else {
                    icon.removeClass('liked');
                }
            },
            error: function(xhr, errmsg, err) {
                console.log(err);
            }
        });
    });
});


</script>


<script>
    function copyToClipboard(){
        const url = window.location.href;
        navigator.clipboard.writeText(url)

        .then(() => {
            const popup = document.getElementById('popup-message');
            popup.style.display = 'flex';
            setTimeout(() => {
            popup.style.display = 'none';
            }, 2000); // Hide the message after 2 seconds
    })
    .catch((err) => {
      // Error occurred while copying
      console.error('Failed to copy URL: ', err);
    });

    }
   
</script>


    {% endblock %}


    

    